// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7IDgHnwpgvHKoTeHDJRXgsybw2c0zrv0',
    appId: '1:97034952930:web:bbdcaebbc5ef124edf7ebb',
    messagingSenderId: '97034952930',
    projectId: 'task1-4e346',
    authDomain: 'task1-4e346.firebaseapp.com',
    storageBucket: 'task1-4e346.firebasestorage.app',
    measurementId: 'G-9VS65V2DJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr735N23TZNCwPKHnfOwia_J3EnkHA8mc',
    appId: '1:97034952930:android:86178db787e08c29df7ebb',
    messagingSenderId: '97034952930',
    projectId: 'task1-4e346',
    storageBucket: 'task1-4e346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw06ohDugSmB9pUuiAJnM8hquMcGALk3c',
    appId: '1:97034952930:ios:90d5328c260ccd7cdf7ebb',
    messagingSenderId: '97034952930',
    projectId: 'task1-4e346',
    storageBucket: 'task1-4e346.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw06ohDugSmB9pUuiAJnM8hquMcGALk3c',
    appId: '1:97034952930:ios:90d5328c260ccd7cdf7ebb',
    messagingSenderId: '97034952930',
    projectId: 'task1-4e346',
    storageBucket: 'task1-4e346.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7IDgHnwpgvHKoTeHDJRXgsybw2c0zrv0',
    appId: '1:97034952930:web:d18f6482b69ae604df7ebb',
    messagingSenderId: '97034952930',
    projectId: 'task1-4e346',
    authDomain: 'task1-4e346.firebaseapp.com',
    storageBucket: 'task1-4e346.firebasestorage.app',
    measurementId: 'G-77LKH617GK',
  );
}
